import Head from "next/head";
import Image from "next/image";
import CheckoutContainer from "../components/CheckoutContainer";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div className="flex flex-col h-screen justify-between">
      <Head>
        <title>Simple SMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <CheckoutContainer />
      </main>

      <Footer />
    </div>
  );
}
